app:

  # it will use the local Dockerfile
  build: .
  environment:
    - NODE_ENV=production
  ports:
    - "3000:3000"
  links:
    - neo4j

neo4j:
  image: neo4j:3.3.5
  environment:
    - NEO4J_dbms_connector_http_address=0.0.0.0:7474
  ports:
    - "7473:7473"
    - "7474:7474"
    - "7687:7687"
  volumes:
    - ./db/dbms:/data/dbms
    - $HOME/neo4j/data:/data
    - $HOME/neo4j/logs:/logs
